s=input("enter a sentence: ")
print(s.upper())
print(s.lower())
print(s.title())
print(len(s))
print(len(s.split()))
print(s.count("a"))
print(s.replace(" ","_"))
print(s.split()[0])
print(s.split()[-1])